import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Dynamic Routing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <link rel="icon" href="/favicon.ico" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-0 m-0 flex bg-white text-black
        justify-between items-center flex-col h-[100vh] w-[100vw]` }>
          <h1 className='text-red-500 font-bold text-3xl'>Header</h1>
        {children}
        <h1 className='text-red-500 font-bold text-3xl'>Footer</h1>
      </body>
    </html>
  );
}
